#!/usr/bin/env bash
#
# Generate .env files for the current worktree
#
# Sources settings.sh (which auto-detects dev/staging/prod), then writes:
#   - <worktree>/frontend/.env  (VITE_-prefixed vars for Vite)
#   - <worktree>/.env           (backend/shared vars)
#
# Usage: cd dev/ && script/generate-env.sh
#        cd staging/ && script/generate-env.sh
#        cd prod/ && script/generate-env.sh
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source the auto-detecting settings
source "$SCRIPT_DIR/settings.sh"

echo "Detected environment: $ENV ($DETECTED_ENV)"
echo "Worktree root: $WORKTREE_ROOT"

# --- Generate frontend/.env (VITE_ prefixed for Vite) ---
FRONTEND_ENV_FILE="$WORKTREE_ROOT/frontend/.env"

cat > "$FRONTEND_ENV_FILE" <<EOF
# Auto-generated by generate-env.sh — do not edit manually
# Environment: $ENV

VITE_API_BASE_URL=http://localhost:$BACKEND_PORT
VITE_FRONTEND_PORT=$FRONTEND_PORT
VITE_BACKEND_PORT=$BACKEND_PORT
VITE_ENV=$ENV
EOF

echo "Wrote $FRONTEND_ENV_FILE"

# --- Generate root .env (backend/shared vars) ---
ROOT_ENV_FILE="$WORKTREE_ROOT/.env"

cat > "$ROOT_ENV_FILE" <<EOF
# Auto-generated by generate-env.sh — do not edit manually
# Environment: $ENV

ENV=$ENV
SERVER_ID=$SERVER_ID
NODE_ENV=$NODE_ENV
DEBUG=$DEBUG

# Ports
FRONTEND_PORT=$FRONTEND_PORT
BACKEND_PORT=$BACKEND_PORT

# Backend
BACKEND_HOST=$BACKEND_HOST
ALLOWED_CORS_DOMAINS=$ALLOWED_CORS_DOMAINS
EOF

echo "Wrote $ROOT_ENV_FILE"
echo "Done."
