#!/usr/bin/env bash
#
# Production environment settings — PLACEHOLDER
# This file is regenerated by Ansible. Do not edit manually.
#
ENV=production
SERVER_ID=1
FRONTEND_PORT=20100
BACKEND_PORT=20101
NODE_ENV=production
DEBUG=false
