#!/usr/bin/env bash
#
# Production environment settings — PLACEHOLDER
# This file is regenerated by Ansible. Do not edit manually.
#
ENV=production
SERVER_ID=1
FRONTEND_PORT=20110
BACKEND_PORT=20111
NODE_ENV=production
DEBUG=false
