#!/usr/bin/env bash
#
# Staging environment settings — PLACEHOLDER
# This file is regenerated by Ansible. Do not edit manually.
#
ENV=staging
SERVER_ID=1
FRONTEND_PORT=17100
BACKEND_PORT=17101
NODE_ENV=staging
DEBUG=false
